use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let instance = std::env::var("LLM_WIKI_INSTANCE").unwrap_or_default();
    println!("cargo:rerun-if-env-changed=LLM_WIKI_INSTANCE");
    match instance.as_str() {
        "" | "test" => {}
        other => panic!("unsupported LLM_WIKI_INSTANCE={other:?}; only `test` is supported"),
    }

    // Release-build guard. The `test` instance is a debug-only developer
    // affordance and must never ship to users. Cargo sets `PROFILE=release` for
    // any profile that inherits from `release` (including cargo-dist's
    // `[profile.dist]`), so this assertion fires on `cargo build --release`,
    // `dist build`, and the dist-autogenerated `.github/workflows/release.yml`
    // path alike. Unlike the `just release-guard` recipe — which only protects
    // the local `just` entrypoints — this guard lives where *every* release
    // build runs and survives `release.yml` regeneration. See
    // wiki/plans/test-instance-namespaced-binary.plan.md Phase 4.
    let profile = std::env::var("PROFILE").unwrap_or_default();
    if instance == "test" && profile == "release" {
        panic!(
            "refusing to build LLM_WIKI_INSTANCE=test in a release profile (PROFILE={profile:?}); \
             the test instance is a debug-only developer affordance and must never ship"
        );
    }
    println!("cargo:rustc-env=LLM_WIKI_COMPILED_INSTANCE={instance}");
    let binary_stem = if instance == "test" {
        "llm-wiki-test"
    } else {
        "llm-wiki"
    };
    println!("cargo:rustc-env=LLM_WIKI_COMPILED_BINARY_STEM={binary_stem}");

    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    if let Ok(target) = std::env::var("TARGET") {
        println!("cargo:rustc-env=LLM_WIKI_BUILD_TARGET={target}");
    }
    println!("cargo:rerun-if-changed=templates");

    validate_templates(&root.join("templates"));
}

fn read(path: &Path) -> String {
    fs::read_to_string(path)
        .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()))
}

fn validate_templates(path: &Path) {
    if path.is_dir() {
        for entry in fs::read_dir(path)
            .unwrap_or_else(|err| panic!("failed to read {}: {err}", path.display()))
        {
            let entry = entry.expect("template directory entry");
            validate_templates(&entry.path());
        }
        return;
    }

    if path.extension().and_then(|extension| extension.to_str()) == Some("md") {
        println!("cargo:rerun-if-changed={}", path.display());
        read(path);
    }
}
